trest12/blog/urls.py
from django.contrib.flatpages import views
from django.urls import include, path, re_path
from .blog_views import (
    PostListView,
    PostDetailView,
    SendContact,
    SearchResultsView,
)
from . import blog_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', blog_views.home, name='blog-home'),
    path('about/', blog_views.about, name='blog-about'),
    path('новости/', PostListView.as_view(), name='новости'),
    path('новости/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('pages/', include('django.contrib.flatpages.urls')),
    # path('form/', blog_views.snippet_detail),
    path('contact-form/', SendContact.as_view(), name="contact-form"),
    path('search_results/', SearchResultsView.as_view(), name='search_results'),
]


# Your other patterns here
urlpatterns += [
    re_path(r'^(?P<url>.*/)$', views.flatpage),
    path('контакты/', views.flatpage, {'url': '/контакты/'}, name='контакты'),
    path('о-компании/', views.flatpage, {'url': '/о-компании/'}, name='о-компании'),
    path('цены/', views.flatpage, {'url': '/цены/'}, name='цены'),
    path('услуги/', views.flatpage, {'url': '/услуги/'}, name='услуги'),
    path('отзывы/', views.flatpage, {'url': '/отзывы/'}, name='отзывы'),
    # backblock services
    path('технический-надзор/', views.flatpage, {'url': '/технический-надзор/'}, name='технический-надзор'),
    path('инженерные-изыскания/', views.flatpage, {'url': '/инженерные-изыскания/'}, name='инженерные-изыскания'),
    path('обследование-зданий-и-сооружений/', views.flatpage, {'url': '/обследование-зданий-и-сооружений/'}, name='обследование-зданий-и-сооружений'),
    path('проектирование/', views.flatpage, {'url': '/проектирование/'}, name='проектирование'),
    path('строительно-техническая-экспертиза/', views.flatpage, {'url': '/строительно-техническая-экспертиза/'}, name='строительно-техническая-экспертиза'),
    path('аутсорсинг-пто/', views.flatpage, {'url': '/аутсорсинг-пто/'}, name='аутсорсинг-пто'),
    path('строительный-аудит/', views.flatpage, {'url': '/строительный-аудит/'}, name='строительный-аудит'),
    path('составление-и-проверка-смет/', views.flatpage, {'url': '/составление-и-проверка-смет/'}, name='составление-и-проверка-смет'),
    path('пре-девелопмент-объектов-недвижимости/', views.flatpage, {'url': '/пре-девелопмент-объектов-недвижимости/'}, name='пре-девелопмент-объектов-недвижимости'),
    path('геодезическое-сопровождение/', views.flatpage, {'url': '/геодезическое-сопровождение/'}, name='геодезическое-сопровождение'),
]

# function displays downloaded pictures
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trest12/trest12/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

trest12/blog/models.py
from django.utils import timezone
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import Q
from django.contrib.flatpages.models import FlatPage
from django.core.mail import send_mass_mail

class ArticleManager(models.Manager):
    use_for_related_fields = True

    def search(self, query=None):
        qs = self.get_queryset()
        if query:
            or_lookup = (Q(title__icontains=query) | Q(content__icontains=query))
            qs = qs.filter(or_lookup)

        return qs


class PageList(models.Model):
    url = models.CharField('Адрес страницы',max_length=100)
    title = models.CharField('Заголовок страницы',max_length=200)
    content = models.TextField('Текст стрницы в поиске',blank=True)
    objects = ArticleManager()

    class Meta:
        verbose_name = 'отображение странцы в поиске'
        verbose_name_plural = 'поиск по сайту'



class Post(models.Model):
    title = models.CharField('Заголовок новости', max_length=100)
    content = models.TextField('Основной текст новости')
    description = models.TextField('Краткое описание')
    image = models.ImageField('Загрузить картинку', upload_to='images/', default='images/No_image_available.svg.png')
    date_posted = models.DateTimeField('Дата/время публикации',default=timezone.now)
    objects = ArticleManager()


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'новость'
        verbose_name_plural = 'Новости'


# Migration is done first, so the form must be without RegexValidator validation

class Contacts(models.Model):
    """feedback form"""
    name = models.CharField('Имя', max_length=120)
    email = models.EmailField('Email', max_length=120)
    # phone = models.CharField('Телефон', max_length=15)
    phone = models.CharField('Телефон', max_length=15, validators=[
        RegexValidator(r'^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$')
    ])
    description = models.TextField('Тема звнока', max_length=1000, blank=True, null=True)
    date = models.DateTimeField('Дата/время получения сообщения',default=timezone.now)

    # to be displayed correctly in the admin panel
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'форма обратной связи'
        verbose_name_plural = 'формы обратной связи'


class Images(models.Model):
    name = models.CharField('Название изображения', max_length=50)
    image = models.ImageField('Выбрать изображение', upload_to='images/')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Загрузить изображение'
        verbose_name_plural = 'Изображения'


class SenderEmails(models.Model):
    subject = models.CharField('Тема сообщения',max_length=150)
    message = models.TextField('Текст сообщения')
    date = models.DateTimeField('Дата отправки', default=timezone.now)
    class Meta:
        verbose_name = 'Добавить рассылку'
        verbose_name_plural = 'Создать рассылку'

trest12/blog/forms.py
from django import forms
from .models import Contacts, SenderEmails

class CheckBox(forms.BooleanField):
    field = forms.CheckboxInput()

class ContactForm(forms.ModelForm):
    checkbox = CheckBox()
    class Meta():
        model = Contacts
        fields = ['name', 'email', 'phone', 'description', 'checkbox']

trest12/blog/templates/blog/about.html
{% extends "blog/base.html" %}
    {% block content %}
        <h1>О компании</h1>
        <p>hello</p>

{% load flatpages %}
{% get_flatpages as flatpages %}
<ul>
    {% for page in flatpages %}
        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
    {% endfor %}
</ul>
{% endblock content %}

trest12/blog/templates/blog/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css'%}">
    <link rel="stylesheet" href="{% static 'blog/css/contactform.css'%}">
    <title>{{ flatpage.title }}</title>
</head>
<body>

    {% include "blog/header.html" %}
    {% include "blog/home-page-elements/backBlock.html" %}
	{% block content %}{% endblock content %}
    {% include "blog/footer.html" %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'blog/js/script.js' %}"></script>
</body>
</html>

trest12/blog/templates/blog/debug_contact_form.html
<!--First variant -->

<a name="feedback">Обратная связь</a>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">submit</button>
</form>
<div class="message">
    {% for message in messages %}
    <p>{% if message.tags %}{% endif %}{{ message }}</p>
    {% endfor %}
</div>


<!--Second variant-->
<a name="feedback">Обратная связь</a>
<form method="post">
    {% csrf_token %}
    {{ form.name }}
    {{ form.email }}
    {{ form.phone }}
    {{ form.description }}
    <button type="submit">submit</button>
</form>
<div class="message">
    {% for message in messages %}
    <p>{% if message.tags %}{% endif %}{{ message }}</p>
    {% endfor %}
</div>

trest12/blog/templates/blog/footer.html
{% load static %}
{% block content %}
<div class="container-fluid desktop">
	<div class="row footer">
		<div class="col-md-6">
			<a href=""><img src="{% static 'blog/images/social/fb.png' %}" width="30"></a>
			<a href=""><img src="{% static 'blog/images/social/ins.png' %}" width="30"></a>
			<a href=""><img src="{% static 'blog/images/social/vk.png' %}" width="30"></a>
			<a href=""><img src="{% static 'blog/images/social/tw.png' %}" width="30"></a>
		</div>
		<div class="col-md-6">
			{% include "blog/form.html" %}
		</div>
	</div>
</div>

<div class="container-fluid mobile">
	<div class="row">
		<div class="col-md-6">
			{% include "blog/form.html" %}
		</div>
		<div class="col-md-6">
			<a href=""><img src="{% static 'blog/images/social/fb.png' %}" width="30"></a>
			<a href=""><img src="{% static 'blog/images/social/ins.png' %}" width="30"></a>
			<a href=""><img src="{% static 'blog/images/social/vk.png' %}" width="30"></a>
			<a href=""><img src="{% static 'blog/images/social/tw.png' %}" width="30"></a>
			<br><br><br>
		</div>
	</div>
</div>

{% endblock content %}

trest12/blog/templates/blog/form.html
<div class="container-fluid">
    <div class="row contact">
        <div class="col-md-12 text-center">
            <a name="feedback">Обратная связь</a>
            <div class="message">
                {% for message in messages %}
                <h5>{% if message.tags %}{% endif %}{{ message }}</h5>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="row contact-form">
        <div class="col-md-12">
            <div id="inline">
                <form method="post" action="{% url 'contact-form' %}">
                    {% csrf_token %}
					<div class="col-md-12">
						<input class="txt" type="text" name="name" maxlength="120" required="" id="id_name" placeholder="Имя">
					</div>
					<div class="col-md-12">
	                    <input class="txt" type="email" name="email" maxlength="120" required="" id="id_email" placeholder="Email">
					</div>
					<div class="col-md-12">
	                    <input class="txt" type="text" name="phone" maxlength="15" required="" id="id_phone" placeholder="Телефон">
					</div>
					<div class="col-md-12">
	                    <textarea class="txtarea" name="description" cols="40" rows="5" maxlength="1000" id="id_description" placeholder="Тема звнока"></textarea>
					</div>
					<div class="col-md-12">
						<p><input class="checkbox" type="checkbox" name="checkbox" required="" id="id_checkbox"> Я соглашаюсь с условиями <a href="">политики конфиденциальности</a>
                    	</p>
                    	<button type="submit" id="send">Отправить</button>
					</div>
                </form>
            </div>
        </div>
    </div>
</div>

trest12/blog/templates/blog/header.html
{% load static %}
{% block content %}
	<div class="container-fluid">
		<div class="row header">
			<div class="col-md-4 logotype">
				<a href="{% url 'blog-home' %}"><h1>трест 12</h1></a>
			</div>
			<div class="col-md-4 text-center">
				<h6>Компания «Трест 12» основана в 1997 году</h6>
				<h6><img src="{% static 'blog/bootstrap-icons/flag.svg' %}" width="24"> г.Самара, ул. Скляренко 26, офис 9010</h6>
			</div>
			<div class="col-md-4 text-center">
				<h6>
					<a href="tel:88463131678">
					<img src="{% static 'blog/bootstrap-icons/tablet.svg' %}" width="24"></a>
					8 (846) 313-16-78
				</h6>
				<h6>
					<a href="mailto:trest12_1@mail.ru"><img src="{% static 'blog/bootstrap-icons/envelope.svg' %}" width="24"></a>
					info@трест12.рф
				</h6>
			</div>
		</div>
	</div>

	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12 navbar-row">
				<nav class="navbar navbar-expand-lg navbar-light bg-light">
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
				<h6>МЕНЮ</h6>
				</button>
					<div class="collapse navbar-collapse" id="navbarSupportedContent">
						<ul class="navbar-nav mr-auto">
							<li class="nav-item">
								<a class="nav-link" href="{% url 'о-компании' %}">О компании</a>
							</li>
							<li class="nav-item">
								<a class="nav-link dropdown-toggle services" href="{% url 'услуги' %}" role="button" aria-haspopup="true" aria-expanded="false">услуги</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{% url 'цены' %}">цены</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{% url 'новости' %}">Новости</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{% url 'отзывы' %}">отзывы</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{% url 'контакты' %}">Контакты</a>
							</li>
						</ul>
						<form class="form-inline my-2 my-lg-0" action="{% url 'search_results' %}" method="get">
						  	<input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="q">
						  	<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
						</form>
					</div>
				</nav>
			</div>
		</div>
	</div>
{% endblock content %}

trest12/blog/templates/blog/home-page-elements/about_company.html
{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12 slider">
			<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
				<ol class="carousel-indicators">
					<li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
					<li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
				</ol>
				<div class="carousel-inner">
					<div class="carousel-item active">
						<div class="col-md-8 slider-content">
							<h1>Сопровождение и контроль строительства</h1>
							<h4>Краткое описание предложения, чтобы было сразу ясно и понятно!</h4>
						</div>
					</div>
					<div class="carousel-item">
						<div class="col-md-8 slider-content">
							<h1>Проектирование зданий и сооружений</h1>
							<h4>Краткое описание предложения, чтобы было сразу ясно и понятно!</h4>
						</div>
					</div>
				</div>
			</div>
			<a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
				<span class="carousel-control-prev-icon" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
			</a>
			<a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
				<span class="carousel-control-next-icon" aria-hidden="true"></span>
				<span class="sr-only">Next</span>
			</a>
		</div>
	</div>
</div>
{% endblock content %}

trest12/blog/templates/blog/home-page-elements/backBlock.html
{% load static %}
{% block content %}
<div class="container-fluid desktop">
	<div class="backBlock">
		<div class="row">
			<div class="col-md-3 light">
				<a href="{% url 'технический-надзор' %}">
					<p>Технический надзор</p>
					<img src="{% static '/blog/images/services/tex_nadzor.jpg' %}" class="preview">
				</a>
			</div>
			<div class="col-md-3 dark">
				<a href="{% url 'инженерные-изыскания' %}">
					<p>Инженерные изыскания</p>
					<img src="{% static 'blog/images/services/inzhenernye-izyskaniya.jpg' %}" class="preview">
				</a>
			</div>
			<div class="col-md-3 light">
				<a href="{% url 'обследование-зданий-и-сооружений' %}">
					<p>Обследование зданий и сооружений</p>
					<img src="{% static 'blog/images/services/tehnicheskoe-obsledovanie-zdanij-i-sooruzhenij.jpg' %}" class="preview">
				</a>
			</div>
			<div class="col-md-3 dark">
				<a href="{% url 'проектирование' %}">
					<p>Проектирование</p>
					<img src="{% static 'blog/images/services/proektirovanie.png' %}" class="preview">
				</a>
			</div>
		</div>
		<div class="row">
			<div class="col-md-3 dark">
				<a href="{% url 'строительно-техническая-экспертиза' %}">
					<p>Строительно-техническая экспертиза</p>
					<img src="{% static 'blog/images/services/stroitelnaya-ekspertiza.jpg' %} " class="preview">
				</a>
			</div>
			<div class="col-md-3 light">
				<a href="{% url 'аутсорсинг-пто' %}">
					<p>Аутсорсинг ПТО</p>
					<img src="{% static 'blog/images/services/autsorsing-pto.jpg' %} " class="preview">
				</a>
			</div>
			<div class="col-md-3 dark">
				<a href="{% url 'строительный-аудит' %}">
					<p>Строительный аудит</p>
					<img src="{% static 'blog/images/services/troi_audit.jpg' %} " class="preview">
				</a>
			</div>
			<div class="col-md-3 light">
				<a href="{% url 'составление-и-проверка-смет' %}">
					<p>Составление и проверка смет</p>
					<img src="{% static 'blog/images/services/sostavlenie-smet.jpg' %} " class="preview">
				</a>
			</div>
		</div>
		<div class="row">
			<div class="col-md-3 light">
				<a href="{% url 'пре-девелопмент-объектов-недвижимости' %}">
					<p>Пре-девелопмент <br> объектов недвижимости</p>
					<img src="{% static 'blog/images/services/pre-development-smrte.jpg' %} " class="preview">
				</a>
			</div>
			<div class="col-md-3 dark">
				<a href="{% url 'геодезическое-сопровождение' %}">
					<p>Геодезическое <br> сопровождение</p>
					<img src="{% static 'blog/images/services/geodez.jpg' %}" class="preview">
				</a>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

trest12/blog/templates/blog/home-page-elements/partners.html
{% load static %}
{% block content %}
<div class="container-fluid">
	<div class="row partners">
		<div class="col-md-12 text-center">
			<h4>Наши партнеры</h4>
		</div>
	</div>
</div>
<div class="container-fluid bottom_filter">
	<div class="row partner">
		<div class="right pointer" onclick="$('.bottom_filter .item_partner:last').insertBefore($('.bottom_filter .item_partner:first'));">
			<img src="{% static 'blog/bootstrap-icons/arrow-right-square-fill.svg' %}" width="36">
		</div>
		<div class="col-md-3 item_partner">
			<a href="https://www.amond.ru/">
				<img class="partners-img" src="{% static 'blog/images/partners/amond.png' %}" alt="">
			</a>
		</div>
		<div class="col-md-3 item_partner">
			<a href="https://www.etm.ru/">
				<img class="partners-img" src="{% static 'blog/images/partners/ETM-25_razvodyaschaya.png' %}" alt="">
			</a>
		</div>
		<div class="col-md-3 item_partner">
			<a href="https://eburg.kuvalda.ru/">
				<img class="partners-img" src="{% static 'blog/images/partners/kuvaldaru.png' %}" alt="">
			</a>
		</div>
		<div class="col-md-3 item_partner">
			<a href="https://contrpro.ru/">
				<img class="partners-img" src="{% static 'blog/images/partners/contrpro-project.png' %}" alt="">
			</a>
		</div>
		<div class="col-md-3 item_partner">
			<a href="https://svgk.ru/">
				<img class="partners-img" src="{% static 'blog/images/partners/sgvk.png' %}" alt="">
			</a>
		</div>
		<div class="col-md-3 item_partner">
			<a href="http://integra63.ru/">
				<img class="partners-img" src="{% static 'blog/images/partners/integra.jpg' %}" alt="">
			</a>
		</div>
		<div class="col-md-3 item_partner">
			<a href="http://kdpmk.narod.ru/">
				<img class="partners-img" src="{% static 'blog/images/partners/kuibishevskoe dorojnoe_pmk.png' %}" alt="">
			</a>
		</div>
		<div class="col-md-3 item_partner">
			<a href="https://www.rosneft.ru/">
				<img class="partners-img" src="{% static 'blog/images/partners/rosneft.png' %}" alt="">
			</a>
		</div>
		<div class="col-md-3 item_partner">
			<a href="http://stkrb.ru/">
				<img class="partners-img" src="{% static 'blog/images/partners/srk.png' %}" alt="">
			</a>
		</div>
		<div class="col-md-3 item_partner">
			<a href="http://kpd63.ru/">
				<img class="partners-img" src="{% static 'blog/images/partners/zavodkpd.png' %}" alt="">
			</a>
		</div>
		<div class="col-md-3 item_partner">
			<a href="http://sumr3.ru/">
				<img class="partners-img" src="{% static 'blog/images/partners/specialnoe_mehanizirovanoe_upravlenie_rabot_3.png' %}" alt="">
			</a>
		</div>
		<div class="col-md-3 item_partner">
			<a href="https://silikat-12.pulscen.ru/">
				<img class="partners-img" src="{% static 'blog/images/partners/silikat.png' %}" alt="">
			</a>
		</div>
		<div class="left pointer" onclick="$('.bottom_filter .item_partner:first').insertAfter($('.bottom_filter .item_partner:last'));">
			<img src="{% static 'blog/bootstrap-icons/arrow-left-square-fill.svg' %}" width="36">
		</div>
	</div>
</div>
{% endblock content %}

trest12/blog/templates/blog/home-page-elements/projects.html
{% load static %}
{% block content %}
	<div class="container-fluid">
		<div class="row your-projects">
			<div class="col-md-12 text-center">
				<h4>Наиболее крупные реализованные проекты</h4>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 text-center ofer-1">
				<h5>Строительство двух пятиэтажных кирпичных четырех секционных домов (№8,9 по генплану) Южный город 12 квартал.</h5>
				<h6>Дата начала проекта: 2015 год</h6>
				<h6>Дата завершения проекта: 2016 год</h6>
				<h6>Сметная стоимость проекта: 230 000 000 руб.</h6>
				<h6>Площадь объекта 10 600 кв.м.</h6>
			</div>
			<div class="col-md-6 text-center ofer-2">
				<h5>Устройство пристенного дренажа, пожарного водопровода и ливневой канализации на объекте: «Семейный Торговый Центр «МЕГА Самара»»</h5>
				<h6>Дата начала проекта: 2008 год</h6>
				<h6>Дата завершения проекта: 2008 год</h6>
				<h6>Сметная стоимость проекта: 6 000 000 руб.</h6>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4 text-center ofer-3">
				<h5>Кирпичный двух секционный 15-ти этажный жилой дом город Самара, Московское шоссе, 399а </h5>
				<h6>Дата начала проекта: 2001 год</h6>
				<h6>Дата завершения проекта: 2003 год</h6>
				<h6>Сметная стоимость проекта: 156 000 000 руб.</h6>
			</div>
			<div class="col-md-4 text-center ofer-4">
				<h5>Автостоянка закрытого типа город Самара 6-я просека, 146</h5>
				<h6>Дата начала проекта: 2007 год</p>
				<h6>Дата завершения проекта: 2008 год</p>
				<h6>Сметная стоимость проекта: 81 380 000 руб.</p>
			</div>
			<div class="col-md-4 text-center ofer-5 ">
				<h5>Строительство кирпичного двух секционного 16-ти этажного жилого дома Карла Маркса, 245</h5>
				<h6>Дата начала проекта: 2004 год</h6>
				<h6>Дата завершения проекта: 2007 год</h6>
				<h6>Сметная стоимость проекта: 180 000 000 руб.</h6>
			</div>
		</div>
	</div>
{% endblock content %}

trest12/blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
    {% include "blog/home-page-elements/backBlock.html" %}
    {% include "blog/home-page-elements/about_company.html" %}
    {% include "blog/home-page-elements/projects.html" %}
    {% include "blog/home-page-elements/partners.html" %}
{% endblock content %}

trest12/blog/templates/blog/news.html
{% extends "blog/base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            {% for post in posts %}
                <p><a class="article-title" href="{% url 'post-detail' post.id %}"><h4>{{ post.title }}</h4></a></p>
                <p>{{ post.date_posted | date:"d.m.Y" }}</p>
                <p>{{ post.description }}</p>
            {% endfor %}
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
           {% if is_paginated %}
                {% if page_obj.has_previous %}
                <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                  <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                  <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% endif %}
                {% endfor %}

              {% if page_obj.has_next %}
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
              {% endif %}

            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

trest12/blog/templates/sendmails.html
{% extends "admin/base_site.html" %}
{% block content %}
<h1>Это рассылка сообщений!</h1>
<h3>При нажатии на кнопку отправки будет произведена рассылка.</h3>
<h3>Рассылка сохранится после отправки</h3>
    <form method="post">
        {% csrf_token %}
        <div class="col-md-12">
            <input class="txt" type="text" name="subject" maxlength="120" required="" id="id_subject" placeholder="тема сообщения">
        </div>
        <div class="col-md-12">
            <textarea class="txtarea" name="message" id="id_message" cols="50" rows="5" maxlength="1000"
                                  id="id_description" placeholder="текст сообщения"></textarea>
        </div>
            <input type="submit" value="Отправить ссобщение пользователям" name="send">
    </form>
{% endblock %}